/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MoreRouteImport } from './routes/more'
import { Route as KinesiotherapyRouteImport } from './routes/kinesiotherapy'
import { Route as EsdmRouteImport } from './routes/esdm'
import { Route as DevelopmentGamesRouteImport } from './routes/development-games'
import { Route as ToysRouteImport } from './routes/toys'
import { Route as IndexRouteImport } from './routes/index'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const KinesiotherapyRoute = KinesiotherapyRouteImport.update({
  id: '/kinesiotherapy',
  path: '/kinesiotherapy',
  getParentRoute: () => rootRouteImport,
} as any)
const EsdmRoute = EsdmRouteImport.update({
  id: '/esdm',
  path: '/esdm',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentGamesRoute = DevelopmentGamesRouteImport.update({
  id: '/development-games',
  path: '/development-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysRoute = ToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/development-games': typeof DevelopmentGamesRoute
  '/toys': typeof ToysRoute
  '/esdm': typeof EsdmRoute
  '/kinesiotherapy': typeof KinesiotherapyRoute
  '/more': typeof MoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/development-games': typeof DevelopmentGamesRoute
  '/toys': typeof ToysRoute
  '/esdm': typeof EsdmRoute
  '/kinesiotherapy': typeof KinesiotherapyRoute
  '/more': typeof MoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/development-games': typeof DevelopmentGamesRoute
  '/toys': typeof ToysRoute
  '/esdm': typeof EsdmRoute
  '/kinesiotherapy': typeof KinesiotherapyRoute
  '/more': typeof MoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/development-games'
    | '/toys'
    | '/esdm'
    | '/kinesiotherapy'
    | '/more'
    | '/sitemap.xml'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/development-games'
    | '/toys'
    | '/esdm'
    | '/kinesiotherapy'
    | '/more'
    | '/sitemap.xml'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/development-games'
    | '/toys'
    | '/esdm'
    | '/kinesiotherapy'
    | '/more'
    | '/sitemap.xml'
    | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopmentGamesRoute: typeof DevelopmentGamesRoute
  ToysRoute: typeof ToysRoute
  EsdmRoute: typeof EsdmRoute
  KinesiotherapyRoute: typeof KinesiotherapyRoute
  MoreRoute: typeof MoreRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesiotherapy': {
      id: '/kinesiotherapy'
      path: '/kinesiotherapy'
      fullPath: '/kinesiotherapy'
      preLoaderRoute: typeof KinesiotherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esdm': {
      id: '/esdm'
      path: '/esdm'
      fullPath: '/esdm'
      preLoaderRoute: typeof EsdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-games': {
      id: '/development-games'
      path: '/development-games'
      fullPath: '/development-games'
      preLoaderRoute: typeof DevelopmentGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys': {
      id: '/toys'
      path: '/toys'
      fullPath: '/toys'
      preLoaderRoute: typeof ToysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopmentGamesRoute: DevelopmentGamesRoute,
  ToysRoute: ToysRoute,
  EsdmRoute: EsdmRoute,
  KinesiotherapyRoute: KinesiotherapyRoute,
  MoreRoute: MoreRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
